# listen binds ticker to specific address and port
listen: "127.0.0.1:__PORT__"
# log_level sets log level for logrus
log_level: "error"
# configuration for the database
database:
  type: "postgres" # postgres, mysql, sqlite
  dsn: postgres: "host=localhost port=5432 user=__DB_USER__ dbname=__DB_NAME__ password=__DB_PWD__ sslmode=disable"
# secret used for JSON Web Tokens
secret: "<your special little secret> (make it LOOOONG!)"
# telegram configuration
telegram:
  token: "" # telegram bot token
# signal group configuration
signal_group:
  api_url: "" # URL to your signal cli (https://github.com/AsamK/signal-cli)
  avatar: "" # URL to the avatar for the signal group
  account: "" # phone number for the signal account
# listen port for prometheus metrics exporter
metrics_listen: ":8181"
upload:
    # path where to store the uploaded files
    path: "__DATA_DIR__"
    # base url for uploaded assets
    url: "http://127.0.0.1:__PORT__"